## IMPORTING LIBRARIES

In [1]:
import pandas as pd
import numpy as np

## IMPORTING DATASET

In [2]:
#We use this when files are inside folder
import os
# Folder path 
path = r"C:\Users\Aditya Singh\Downloads\archive (4)"

# Load datasets
orders = pd.read_csv(os.path.join(path, "olist_orders_dataset.csv"))
order_items = pd.read_csv(os.path.join(path, "olist_order_items_dataset.csv"))
products = pd.read_csv(os.path.join(path, "olist_products_dataset.csv"))
customers = pd.read_csv(os.path.join(path, "olist_customers_dataset.csv"))
reviews = pd.read_csv(os.path.join(path, "olist_order_reviews_dataset.csv"))
category_translation = pd.read_csv(os.path.join(path, "product_category_name_translation.csv"))

print("Files loaded successfully")

Files loaded successfully

In [3]:
orders.head()
orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  str
 1   customer_id                    99441 non-null  str
 2   order_status                   99441 non-null  str
 3   order_purchase_timestamp       99441 non-null  str
 4   order_approved_at              99281 non-null  str
 5   order_delivered_carrier_date   97658 non-null  str
 6   order_delivered_customer_date  96476 non-null  str
 7   order_estimated_delivery_date  99441 non-null  str
dtypes: str(8)
memory usage: 21.9 MB

In [4]:
## CHECKING FOR NULL VALUE
orders.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [5]:
## CHECKING FREQUENCY
orders['order_status'].value_counts(normalize=True) * 100

order_status
delivered      97.020344
shipped         1.113223
canceled        0.628513
unavailable     0.612423
invoiced        0.315765
processing      0.302692
created         0.005028
approved        0.002011
Name: proportion, dtype: float64

In [6]:
orders.duplicated().sum()

np.int64(0)

In [8]:
orders['order_purchase_timestamp'] = pd.to_datetime(orders['order_purchase_timestamp'])

orders['order_year'] = orders['order_purchase_timestamp'].dt.year
orders['order_month'] = orders['order_purchase_timestamp'].dt.strftime('%Y-%m')

In [9]:
orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_year,order_month
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,2017,2017-10
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00,2018,2018-07
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00,2018,2018-08
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00,2017,2017-11
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00,2018,2018-02

In [10]:
products.shape

(32951, 9)

In [11]:
products.info()

<class 'pandas.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  str
 1   product_category_name       32341 non-null  str
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), str(2)
memory usage: 3.7 MB

In [12]:
products.head()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

In [161]:
## CHECKING SUM OF DUPLICATES
products.duplicated().sum()

np.int64(0)

In [164]:
## FINDING SUM OF NULL VALUES IN PRODUCT DATASET
products.isnull().sum()

product_id               0
product_category_name    0
dtype: int64

In [165]:
## FILLING NULL VALUES WITH N/A
products['product_category_name'] = products['product_category_name'].fillna('N/A')

In [166]:
## SELECTING COLUMNS AND REMOVING UNECESSARY ONES
products = products[['product_id', 'product_category_name']]

In [118]:
products.head()

                         product_id  product_category_name
0  1e9e8ef04dbcff4541ed26657ea517e5             perfumaria
1  3aa071139cb16b67ca9e5dea641aaa2f                  artes
2  96bd76ec8810374ed1b65e291975717f          esporte_lazer
3  cef67bcfe19066a932b7673e239eb23d                  bebes
4  9dc1a7de274444849c219cff195d0b71  utilidades_domesticas

In [107]:
order_items.info()

<class 'pandas.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 3 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   order_id    112650 non-null  str
 1   product_id  112650 non-null  str
 2   revenue     112650 non-null  float64
dtypes: float64(1), str(2)
memory usage: 2.6 MB

In [ ]:
## FINDING REVENUE
order_items['revenue']=order_items['freight_value']+order_items['price']

In [109]:
order_items.head()

                           order_id                        product_id  revenue
0  00010242fe8c5a6d1ba2dd792cb16214  4244733e06e7ecb4970a6e2683c13e61    72.19
1  00018f77f2f0320c557190d7a144bdd3  e5f2d52b802189ee658865ca93d83a8f   259.83
2  000229ec398224ef6ca0657da4fc703e  c777355d18b72b67abbeef9df44fd0fd   216.87
3  00024acbcdf0a6daa1e931b038114c75  7634da152a4610f1595efa32f14722fc    25.78
4  00042b26cf59d7ce69dfabb4e55b4fd9  ac6c3623068f30de03045865e4e10089   218.04

In [105]:
customers.shape
customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   customer_id     99441 non-null  str
 1   customer_city   99441 non-null  str
 2   customer_state  99441 non-null  str
dtypes: str(3)
memory usage: 2.3 MB

In [110]:
customers.isnull().sum()
customers.duplicated().sum()

np.int64(0)

In [167]:
## SELECTING COLUMNS AND REMOVING UNECESSARY ONES
customers = customers[
    ['customer_id', 'customer_city', 'customer_state']
]

In [112]:
customers.head()

                        customer_id          customer_city customer_state
0  06b8999e2fba1a1fbc88172c00ba8bc7                 franca             SP
1  18955e83d337fd6b2def6b18a428ac77  sao bernardo do campo             SP
2  4e7b3e00288586ebd08712fdd0374a03              sao paulo             SP
3  b2b6027bc5c5109e529d4dc6358b12c3        mogi das cruzes             SP
4  4f2d8ab171c80ec8364f7c12e35b23ad               campinas             SP

In [89]:
category_translation.shape
category_translation.info()

<class 'pandas.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 2 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   product_category_name          71 non-null     str
 1   product_category_name_english  71 non-null     str
dtypes: str(2)
memory usage: 1.2 KB

In [168]:
## CHECKING SUM OF DUPLICATES
category_translation.duplicated().sum()

np.int64(0)

In [151]:
reviews.shape

(99224, 2)

In [92]:
reviews.info()

<class 'pandas.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   order_id      99224 non-null  str
 1   review_score  99224 non-null  int64
dtypes: int64(1), str(1)
memory usage: 1.5 MB

In [93]:
reviews.isnull().sum()

order_id        0
review_score    0
dtype: int64

In [169]:
## SELECTING COLUMNS AND REMOVING UNECESSARY ONES
reviews = reviews[['order_id', 'review_score']]

In [95]:
reviews.head()

                           order_id  review_score
0  73fc7af87114b39712e6da79b0a377eb             4
1  a548910a1c6147796b98fdf73dbeba33             5
2  f9e4b658b201a9f2ecdecbb34bed034b             5
3  658677c97b385a9be170737859d3511b             5
4  8e6bfb81e283fa7e4f11123a3fb894f1             5

In [96]:
reviews['review_score'].value_counts().sort_index()

review_score
1    11424
2     3151
3     8179
4    19142
5    57328
Name: count, dtype: int64

In [171]:
## MERGING ALL CLEANED DATASETS INTO FINAL DATASET
df=pd.merge(orders,order_items ,on='order_id',how='left')
df=pd.merge(df,products , on ='product_id',how='left')
df = pd.merge(df,category_translation,on='product_category_name',how='left')
df = pd.merge(df,customers,on='customer_id',how='left')
final_df = pd.merge(df,reviews,on='order_id',how='left')

In [142]:
final_df.shape

(114092, 17)

In [143]:
final_df.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_year,order_month,product_id,revenue,product_category_name,product_category_name_english,customer_city,customer_state,review_score
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,2017,2017-10,87285b34884572647811a353c7ac498a,38.71,utilidades_domesticas,housewares,sao paulo,SP,4.0
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,2018,2018-07,595fac2a385ac33a80bd5114aec74eb8,141.46,perfumaria,perfumery,barreiras,BA,4.0
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,2018,2018-08,aa4383b373c6aca5d8797843e5594415,179.12,automotivo,auto,vianopolis,GO,5.0
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,2017,2017-11,d0b61bfb1de832b15ba9d266ca96e5b0,72.20,pet_shop,pet_shop,sao goncalo do amarante,RN,5.0
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,2018,2018-02,65266b2da20d04dbe00c5c2d3bb7859e,28.62,papelaria,stationery,santo andre,SP,5.0

In [172]:
## DROPPING UNCECCESARY COLUMNS
final_df.drop(columns=['product_category_name'], inplace=True)

In [173]:
## VIEWING COLUMNS IN FINAL DATASET
final_df.columns

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date',
       'order_year', 'order_month', 'product_id', 'revenue',
       'product_category_name_english', 'customer_city', 'customer_state',
       'review_score'],
      dtype='str')

In [146]:
final_df['delivery_days'] = (
    final_df['order_delivered_customer_date']
    - final_df['order_purchase_timestamp']
).dt.days

In [147]:
final_df.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_year,order_month,product_id,revenue,product_category_name_english,customer_city,customer_state,review_score,delivery_days
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,2017,2017-10,87285b34884572647811a353c7ac498a,38.71,housewares,sao paulo,SP,4.0,8.0
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,2018,2018-07,595fac2a385ac33a80bd5114aec74eb8,141.46,perfumery,barreiras,BA,4.0,13.0
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,2018,2018-08,aa4383b373c6aca5d8797843e5594415,179.12,auto,vianopolis,GO,5.0,9.0
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,2017,2017-11,d0b61bfb1de832b15ba9d266ca96e5b0,72.20,pet_shop,sao goncalo do amarante,RN,5.0,13.0
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,2018,2018-02,65266b2da20d04dbe00c5c2d3bb7859e,28.62,stationery,santo andre,SP,5.0,2.0

In [183]:
## SORTING VALUES IN ASCENDING ORDER
final_df.isnull().sum().sort_values(ascending=False)

order_delivered_customer_date    2475
order_delivered_carrier_date     1203
review_score                      942
order_approved_at                  15
order_purchase_timestamp            0
order_status                        0
customer_id                         0
order_id                            0
order_estimated_delivery_date       0
order_year                          0
product_id                          0
order_month                         0
revenue                             0
product_category_name_english       0
customer_city                       0
customer_state                      0
dtype: int64

In [175]:
## FILLING NULL VALUES WITH UNKNOWN
final_df['product_category_name_english'] = (
    final_df['product_category_name_english']
    .fillna('Unknown')
)

In [176]:
## ROWS WITH MISSING VALUES ARE DELETED
final_df = final_df[final_df['revenue'].notna()]

In [177]:
final_df.isnull().sum().sort_values(ascending=False)

order_delivered_customer_date    2475
order_delivered_carrier_date     1203
review_score                      942
order_approved_at                  15
order_purchase_timestamp            0
order_status                        0
customer_id                         0
order_id                            0
order_estimated_delivery_date       0
order_year                          0
product_id                          0
order_month                         0
revenue                             0
product_category_name_english       0
customer_city                       0
customer_state                      0
dtype: int64

In [179]:
## EXPORTING FINAL DATASET
output_path =r"C:\Users\Aditya Singh\Downloads\archive (4)"
os.makedirs(output_path ,exist_ok=True)
final_df.to_csv(os.path.join(output_path,"olist_cleaned.csv"),index=False)
print("File Cleaned")

File Cleaned

In [182]:
final_df['order_year'].head()
final_df['order_year'].dtype

dtype('int32')

In [186]:
final_df.dtypes

order_id                                    str
customer_id                                 str
order_status                                str
order_purchase_timestamp         datetime64[us]
order_approved_at                datetime64[us]
order_delivered_carrier_date     datetime64[us]
order_delivered_customer_date    datetime64[us]
order_estimated_delivery_date    datetime64[us]
order_year                                int32
order_month                                 str
product_id                                  str
revenue                                 float64
product_category_name_english               str
customer_city                               str
customer_state                              str
review_score                            float64
dtype: object